<a href="https://colab.research.google.com/github/arthireddy14/Deep_Learning/blob/main/smart_loan_approval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Smart Loan Approval System

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

A fintech company wants to automate loan approval using Al.

Each applicant has:

· X1 - Income Level (0 = Low, 1 = High)
. X2 - Credit Score Category (0 = Poor, 1 = Good)
Approval Rules (given by domain experts):
. If income is high AND credit score is good - Approve
. If income is low AND credit score is poor - Reject
. If one is high and the other is low - Further investigation - Approve only if credit score is good

This creates the following decision table:

In [2]:
x=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
y=np.array([0,1,0,1])
x,y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 1, 0, 1]))

Upgrade the rule:

New policy:

· Approve if:
. Income is high AND credit is good
. OR income is low AND credit is good
. Reject if:
. Both are poor
. OR income high but credit poor

New truth table:


In [3]:
x=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
y=np.array([0,1,0,1])
x,y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 1, 0, 1]))

Part A – Conceptual
Is this problem linearly separable?
Can single perceptron solve it?
Why or why not?

In [6]:
w=np.array([0.0,1.0])
# weights:ignore income,use credit
# if credit = 1 → Approve (regardless of income).
# If credit = 0 → Reject (regardless of income).

b=-0.5
def perceptron(x):
  z=np.dot(w,x)+b
  return 1 if z>=0 else 0


In [7]:
print("Loan approval results : ")
for xi,yi in zip(x,y):
  pred=perceptron(xi)
  print(f"Input :{xi} ,Expected : {yi}, Predicted : {pred}")

Loan approval results : 
Input :[0 0] ,Expected : 0, Predicted : 0
Input :[0 1] ,Expected : 1, Predicted : 1
Input :[1 0] ,Expected : 0, Predicted : 0
Input :[1 1] ,Expected : 1, Predicted : 1


n1->Weights:
w₁₁ = 0
w₁₂ = 1
w₁₃ = -1
b₁ = -0.5

n2->

Weights:
w₂₁ = 1
w₂₂ = 1
w₂₃ = 0
b₂ = -1.5

n3->

Weights:
w₃₁ = 0
w₃₂ = -1
w₃₃ = 1
b₃ = -0.5

output:
So we assign:
w₄₁ = 1
w₄₂ = 1
w₄₃ = -2
b₄ = -0.5


In [11]:
# hidden layer weights
w11,w12,w13,b1=0,1,-1,-0.5
w21,w22,w23,b2=1,1,0,-1.5
w31,w32,w33,b3=0,-1,1,-0.5
# output weights
w41,w42,w43,b4=1,1,-2,-0.5

In [12]:
def step(z):
  return 1 if z>=0 else 0

In [13]:
def forward_propagation(x1,x2,x3=1):
  h1_1=step(w11*x1+w21*x2+b1)
  h2_1=step(w12*x1+w22*x2+b2)
  h3_1=step(w13*x1+w23*x2+b3)
  y=step(w41*x1+w42*x2+w43*x3+b4)
  return h1_1,h2_1,h3_1,y

Part B – Architecture Design
Design:
3 Inputs → 3 Hidden Neurons → 1 Output
Explain:
What feature each hidden neuron should detect.
Why hidden layer helps.
Part C – Forward Propagation

In [14]:
inputs = [
    (0,0),
    (0,1),
    (1,0),
    (1,1)
]

for x1, x2 in inputs:
    h1, h2, h3, y = forward_propagation(x1, x2)
    print(f"Input: ({x1},{x2}) → Output: {y}")

Input: (0,0) → Output: 0
Input: (0,1) → Output: 0
Input: (1,0) → Output: 0
Input: (1,1) → Output: 0


Now modify further:

Add business risk flag:

. X3 - Existing loan (0 = No, 1 =Yes)

New complex rule:

Approve if:

. Credit is good AND no existing loan
. OR Income high AND credit good

Reject otherwise.

In [15]:
def forward(x1, x2, x3):

    # Hidden layer

    # h1 = X2 AND NOT X3
    h1 = step(1*x2 + (-1)*x3 - 0.5)

    # h2 = X1 AND X2
    h2 = step(1*x1 + 1*x2 - 1.5)

    # Output: OR
    y = step(1*h1 + 1*h2 - 0.5)

    return h1, h2, y

In [16]:
inputs = [
    (0,0,0),
    (0,0,1),
    (0,1,0),
    (0,1,1),
    (1,0,0),
    (1,0,1),
    (1,1,0),
    (1,1,1)
]

for x in inputs:
    h1, h2, y = forward(*x)
    print(f"Input: {x} → Output: {y}")

Input: (0, 0, 0) → Output: 0
Input: (0, 0, 1) → Output: 0
Input: (0, 1, 0) → Output: 1
Input: (0, 1, 1) → Output: 0
Input: (1, 0, 0) → Output: 0
Input: (1, 0, 1) → Output: 0
Input: (1, 1, 0) → Output: 1
Input: (1, 1, 1) → Output: 1
